### PR TITLE
[bugfix] add format and standalone in hi locale

### LINKED ISSUE #5692: Can't parse some months in Hindi locale
**Describe the bug**

Use next parse command:
```
moment(value, ["MMMM DD, YYYY", "MMMM DD YYYY", "DD MMMM YYYY", "DD MMM YYYY", "DD MMM. YYYY", "MMM. DD YYYY", "YYYY/MM/DD", "YYYY/M/DD", "MMM DD YYYY", "MMM DD, YYYY", "MMM. DD, YYYY", "YYYY-MM-DD", "L", "LL", "LLL", "LLLL"], 'hi')
```

Two examples (correct parse and wrong):

1. Try to parse `11 अगस्त 2018` (in ISO format: 2018-08-11). In result we will see Moment object:
```
Moment {
 _isAMomentObject = true
 _i = "11 अगस्त 2018"
 _f = "DD MMMM YYYY"
 _l = "hi"
 _isUTC = false
 _isValid = true
...
```
That is correct, found right date format.

2.  Try to parse `13 फरवरी 2018` (in ISO format: 2018-02-13). In result we will see Moment object:
```
_isAMomentObject = true
_i = "13 फरवरी 2018"
_f = "YYYY/MM/DD"
_l = "hi"
_isUTC = false
_isValid = false
...
```

As you see, found wrong format for this date - "YYYY/MM/DD"

moment lib version: 2.27.0

### **UPDATED**

I wrote jest test for hindi locale:

```
import moment from "moment";

describe('Parse date tests', () => {

    test.each([

        // hindi
        ["11 जनवरी 2018", "hi", new Date(2018, 0, 11)],
        ["11 फरवरी 2018", "hi", new Date(2018, 1, 11)],
        ["11 मार्च 2018", "hi", new Date(2018, 2, 11)],
        ["11 अप्रैल 2018", "hi", new Date(2018, 3, 11)],
        ["11 मई 2018", "hi", new Date(2018, 4, 11)],
        ["11 जून 2018", "hi", new Date(2018, 5, 11)],
        ["11 जुलाई 2018", "hi", new Date(2018, 6, 11)],
        ["11 अगस्त 2018", "hi", new Date(2018, 7, 11)],

        ["11 सितंबर 2018", "hi", new Date(2018, 8, 11)],
        ["11 अक्टूबर 2018", "hi", new Date(2018, 9, 11)],
        ["11 नवंबर 2018", "hi", new Date(2018, 10, 11)],
        ["11 दिसंबर 2018", "hi", new Date(2018, 11, 11)],
    ])('testParseDate %s, %s', (dateStr: string, language: string, mustBe: Date) => {

        var mom = moment(dateStr, ['DD MMMM YYYY'], language);
        var parsed = mom.toDate();
        // console.log(`Parsed: ${parsed}, mustBe: ${mustBe}`);
        // console.log(`Formatted: ${mom.locale('en').format('YYYY-MM-DD')}`);

        expect(parsed.getFullYear())
            .toBe(mustBe.getFullYear());
        expect(parsed.getMonth())
            .toBe(mustBe.getMonth());
        expect(parsed.getDate())
            .toBe(mustBe.getDate());
    });
});
```

Result: moment can't parse next months:

```
फरवरी  - Febrary
सितंबर  - September
नवंबर - November
दिसंबर - December
```

Other months parsed correctly.

### LINKED ISSUE #5739: Moment gives unexpected results in hindi locale
**Describe the bug**
While using this library for my project, I found out that some of the Hindi months are being parsed incorrectly for eg. 
 `moment("16 फरवरी 2020", ["DD MMMM YYYY"], "hi").format("MMMM")`.
This should return:
expected : `"फरवरी"`
but it actually returns : `"जनवरी"`

On more testing I found out that this issue only occurs when I try to parse फरवरी (February), सितंबर (September), नवंबर (November). दिसंबर (December)

**To Reproduce**
`console.log(moment("16 फरवरी 2020", ["DD MMMM YYYY"], "hi").format("MMMM"))`
`console.log(moment("16 सितंबर 2020", ["DD MMMM YYYY"], "hi").format("MMMM"))`
`console.log(moment("16 नवंबर 2020", ["DD MMMM YYYY"], "hi").format("MMMM"))`
`console.log(moment("16 दिसंबर 2020", ["DD MMMM YYYY"], "hi").format("MMMM"))`

**Expected behavior**
 `moment("16 फरवरी 2020", ["DD MMMM YYYY"], "hi").format("MMMM")`.
This should return:
expected :  `फरवरी` (February), `सितंबर` (September), `नवंबर` (November). `दिसंबर` (December)
but it actually returns : `"जनवरी"` for all the above inputs.

### PR DESCRIPTION
**Pull request by PriyaBihani**
fixes #5692  
fixes #5739 

I found out that this is because of the inflections that exists in Hindi language. For example :  दिसंबर (what you wrote)can be written as दिसम्बर(what is written in code), 
सितंबर - सितम्बर,
नवंबर - नवम्बर,
फरवरी - फ़रवरी,
So, in order to resolve this issue I added format and standalone feature like in Russian language.  After modifying locale file of Hindi, I also modified the test/locale/hi.js in order to pass all the tests. 
I have created a pull request to fix this issue. Until, this pull request get accepted the work around is to use these months:  दिसम्बर, सितम्बर, नवम्बर, फ़रवरी.
testCasesPassed

### CODE REVIEW

File: src/test/locale/hi.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import moment from '../../moment';
 localeModule('hi');
 
 test('parse', function (assert) {
-    var tests = 'जनवरी जन._फ़रवरी फ़र._मार्च मार्च_अप्रैल अप्रै._मई मई_जून जून_जुलाई जुल._अगस्त अग._सितम्बर सित._अक्टूबर अक्टू._नवम्बर नव._दिसम्बर दिस.'.split(
+    var tests = 'जनवरी जन._फरवरी फ़र._मार्च मार्च_अप्रैल अप्रै._मई मई_जून जून_जुलाई जुल._अगस्त अग._सितंबर सित._अक्टूबर अक्टू._नवंबर नव._दिसंबर दिस.'.split(
```
Comment (marwahaha) [inline src/test/locale/hi.js:7]: Why are the tests changed? Will both inflections work or just the new one?

Comment (PriyaBihani) [reply src/test/locale/hi.js:7]: Thanks for pointing this out. I have fixed it with the help of regular expressions. Now both the inflections work along with the testcases.

Comment (marwahaha) [reply src/test/locale/hi.js:7]: If both inflections work, could you add tests for both inflections?

Comment (PriyaBihani) [reply src/test/locale/hi.js:7]: @marwahaha  Done. I have added the test using nomination and accusation.

Comment (marwahaha) [reply src/test/locale/hi.js:7]: Could you add parsing tests for both inflections?

File: src/test/locale/hi.js [hunk 2]
```diff
@@ -129,6 +129,30 @@ test('format month', function (assert) {
...
+    for (i = 0; i < 12; i++) {
+        assert.equal(
+            moment([2011, i, 1]).format('D MMMM'),
+            '१ ' + months.accusative[i],
+            '१ ' + months.accusative[i]
+        );
+        assert.equal(
+            moment([2011, i, 1]).format('MMMM'),
+            months.nominative[i],
+            '१ ' + months.nominative[i]
```
Comment (marwahaha) [inline src/test/locale/hi.js:151]: Why does the accusative form need '१ ' but the nominative form doesn't?

File: src/test/locale/hi.js (hunk 1 above)
Comment (PriyaBihani) [reply src/test/locale/hi.js]: @marwahaha I have added the parsing testing for both inflections.

File: src/test/locale/hi.js (hunk 2 above)
Comment (PriyaBihani) [reply src/test/locale/hi.js:173]: If I added day format in nominative then moment won't be able to access standalone's value. Either I can write this ( this is in the current repo): 
```
 assert.equal(
            moment([2011, i, 1]).format('MMMM'),
            months.nominative[i],
            '१ ' + months.nominative[i]
        );
```
Or I can write it like this: 
```
 assert.equal(
            moment([2011, i, 1]).format('D, MMMM'),
            '१, ' + months.nominative[i],
            '१, ' + months.nominative[i]
        );
```
But if I change it to the way you are suggesting me (I think) like this : 
```
  assert.equal(
            moment([2011, i, 1]).format('D MMMM'),
            '१ ' + months.nominative[i],
            '१ ' + months.nominative[i]
        );
```
I am merely asking moment to give me different value for the same input. Moment will give me an accusative value where as I will be checking for nominative.
I would change it to anyway you will suggest. 
PS: I think, we don't even need this test anymore because I have added the test for both inflections in parsing like you asked.

Comment (marwahaha) [reply src/test/locale/hi.js:173]: Oh, you are right. Thanks for clarifying.

**Review by marwahaha — APPROVED** [review]
Awesome!

**Comment by marwahaha** [comment]
I would like to get one more Hindi speaker to approve.
@mayanksinghal @altro3 can you confirm?

**Comment by marwahaha** [comment]
Merging based on discussion in https://github.com/moment/moment/issues/5739
