### PR TITLE
[bugfix] Correct min/max TypeScript signatures

### LINKED ISSUE #4316: moment.max moments[i].isValid is not a function
**Description of the Issue and Steps to Reproduce:**

`moment.max(moment(),new Date())`

**happens when last parameter is not moment**

```
global.js:2673 Uncaught TypeError: moments[i].isValid is not a function
    at pickBy (global.js:2673)
    at Function.max (global.js:2690)
    at <anonymous>:1:8
```

**Environment:**
any

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```
```
Wed Nov 22 2017 15:26:08 GMT+0800 (CST)
VM97:2 2017/11/22 下午3:26:08
VM97:3 -480
VM97:4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
VM97:5 2.19.2
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

### PR DESCRIPTION
**Pull request by ashsearle**
`min` and `max` only work with moment instances (not Dates, strings, numbers etc.)

Fixes #4316

### CODE REVIEW

**Comment by marwahaha** [comment]
Nice.  Could you add some tests in https://github.com/moment/moment/blob/develop/typing-tests/moment-tests.ts ?

I haven't found a good way to do negative testing for typings...

File: moment.d.ts [hunk 1]
```diff
@@ -684,8 +684,8 @@ declare namespace moment {
   export function weekdaysMin(localeSorted: boolean, format: string): string[];
   export function weekdaysMin(localeSorted: boolean, format: string, index: number): string;
 
-  export function min(...moments: MomentInput[]): Moment;
-  export function max(...moments: MomentInput[]): Moment;
+  export function min(...moments: Moment[]): Moment;
+  export function max(...moments: Moment[]): Moment;
```
Comment (lfairy) [inline moment.d.ts]: Can you please add this overload as well?

```ts
export function min(moments: Moment[]): Moment;
```

Similarly for `max`.

(Both methods allow for passing in an array directly, but this is not reflected in the types right now.)
